# Generated by Django 4.1.6 on 2023-02-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["title"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["title"],
                "verbose_name": "Тэг",
                "verbose_name_plural": "Тэги",
            },
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True, verbose_name="Текст новости"),
        ),
    ]
