# Generated by Django 4.1.7 on 2023-03-07 09:08

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0002_menuhome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuhome',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AddField(
            model_name='page',
            name='menuitem',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='siteapp.menuhome', verbose_name='Пункт меню'),
        ),
    ]
