# Generated by Django 4.1.7 on 2023-03-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0003_alter_menuhome_options_page_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuhome',
            name='divider',
            field=models.BooleanField(default=False, verbose_name='Разделитель'),
        ),
    ]
