# Generated by Django 4.1.7 on 2023-03-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0004_menuhome_divider'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuhome',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='Выключение'),
        ),
    ]
